config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/' => redirect('/lectures')
  get '/lectures', to: 'syllabus#index'
  post '/lectures', to: 'syllabus#index'
  get '/lectures/:id', to: 'syllabus#show'
  post '/lectures/:uuid/check', to: 'syllabus#check_lecture'
  get '/my-lectures', to: 'syllabus#my_lecture'
  post '/my-lectures', to: 'syllabus#my_lecture'
  get  '/sync-toyo-app', to: 'syllabus#toyo_app_login'
  post '/sync-toyo-app', to: 'syllabus#toyo_app_sync'

  scope :auth do
    get '/sign_in', to: 'auth#login'
    get '/callback', to: 'auth#callback'
    get '/sign_out', to: 'auth#logout'
  end

  scope :teachers do
    get '/', to: 'teacher#index'
    get '/:id', to: 'teacher#show'
  end

  get 'about', to: 'application#about'
  get 'health', to: 'application#health'

  scope :api do
    get 'keygen', to: 'api#generate_key'

    scope 'my-lectures' do
      get '/', to: 'api#my_lectures'
    end

    scope 'lectures' do
      get '/', to: 'api#lectures'
      get '/:uuid', to: 'api#lecture'
    end

    scope 'teachers' do
      get '/', to: 'api#teachers'
      get '/:uuid', to: 'api#teacher'
    end
  end
end

app/controllers/syllabus_controller.rb
require 'devise'
require 'uri'
require 'net/http'
require 'net/https'

class SyllabusController < ApplicationController
  include Devise::Controllers::Helpers
  protect_from_forgery :only => [:check_lecture]

  def index
    @data = Lecture.all

    @data = @data.where(year: params[:year]) if params[:year].present?
    @data = @data.where(course: params[:course]) if params[:course].present?

    if params[:teacher].present? then
      target_teacher = Teacher.where('name ILIKE ?', "%#{params[:teacher]}%")[0]

      @data = @data.where('teachers @> ARRAY[?]::varchar[]', [target_teacher.uuid]) if target_teacher.present?
    end

    @data = @data.where('target_year @> ARRAY[?]::integer[]', [params[:target_year]]) if params[:target_year].present?
    @data = @data.where("title ILIKE ?", "%#{params[:title]}%") if params[:title].present?

    if params[:quarter].present? then
      @data = if params[:quarter] == "spring" then
                @data.where('quarter @> ARRAY[?]::integer[]', [1,2])
              elsif params[:quarter] == "fall" then
                @data.where('quarter @> ARRAY[?]::integer[]', [3,4])
              else
                @data.where('quarter @> ARRAY[?]::integer[]', [params[:quarter]])
              end
    end

    if params[:include_past_grade] != "on" and params[:target_year].present? then
      @data = @data.where('target_year[1] = ?', params[:target_year])
    end

    respond_to do |format|
      format.html
      format.json {render :json => @data}
    end
  end

  def show
    @data = Lecture.find_by_uuid(params[:id])
    @time = {
        0 => "月曜",
        1 => "火曜",
        2 => "水曜",
        3 => "木曜",
        4 => "金曜",
        5 => "土曜",
        6 => "日曜",
        7 => "集中"
    }[@data.week]

    @time += " / "

    @time += {
        1 => "1限",
        2 => "2限",
        3 => "3限",
        4 => "4限",
        5 => "5限",
        6 => "6限",
        7 => "7限",
        8 => "集中"
    }[@data.time]

    @quarter = if @data.quarter == [1,2] then
                "春学期"
              elsif @data.quarter == [3,4] then
                "秋学期"
              elsif @data.quarter == [0] then
                "集中"
              else
                "#{@data.quarter[0]}Q"
              end

    @available_grade = []
    @data.target_year.each do|grade|
      @available_grade.append("#{grade}年")
    end

    @available_grade = @available_grade.join(",")

    teachers = []
    @data.teachers.each do|teacher|
      teacher_row = Teacher.find_by_uuid(teacher)
      teachers.append(teacher_row.name) if teacher_row.present?
    end

    @teachers = teachers.join(', ')

    @room = if @data.room.present?
              @data.room
            else
              '情報なし'
            end


    respond_to do |format|
      format.html
      format.json {render :json => @data}
    end
  end

  def my_lecture
    unless signed_in?
      session['current_access'] = request.fullpath
      redirect_to sign_in_path
      return
    end

    @data = Lecture.where(:uuid => current_user.registered_lectures)

    @data = @data.where(year: params[:year]) if params[:year].present?
    @data = @data.where(course: params[:course]) if params[:course].present?

    if params[:teacher].present? then
      target_teacher = Teacher.where('name ILIKE ?', "%#{params[:teacher]}%")[0]

      @data = @data.where('teachers @> ARRAY[?]::varchar[]', [target_teacher.uuid]) if target_teacher.present?
    end

    @data = @data.where('target_year @> ARRAY[?]::integer[]', [params[:target_year]]) if params[:target_year].present?
    @data = @data.where("title ILIKE ?", "%#{params[:title]}%") if params[:title].present?

    if params[:quarter].present? then
      @data = if params[:quarter] == "spring" then
                @data.where('quarter @> ARRAY[?]::integer[]', [1,2])
              elsif params[:quarter] == "fall" then
                @data.where('quarter @> ARRAY[?]::integer[]', [3,4])
              else
                @data.where('quarter @> ARRAY[?]::integer[]', [params[:quarter]])
              end
    end

    if params[:include_past_grade] != "on" and params[:target_year].present? then
      @data = @data.where('target_year[1] = ?', params[:target_year])
    end

    respond_to do |format|
      format.html
      format.json {render :json => @data}
    end
  end

  def check_lecture
    unless signed_in? then
      session['current_access'] = request.fullpath
      redirect_to sign_in_path
      return
    end

    lecture = Lecture.find_by_uuid(params[:uuid])
    unless lecture.present?
      redirect_to '/'
      return
    end

    user = User.find_by_id(current_user.id)
    if params['is_register'] == 'on' then
      user.registered_lectures.append(lecture.uuid)
    else
      user.registered_lectures.select! {|a| a != lecture.uuid }
    end

    user.registered_lectures.uniq!
    user.save()

    redirect_back(fallback_location: '/')
  end

  def toyo_app_login
    unless signed_in?
      session['current_access'] = request.fullpath
      redirect_to sign_in_path
      return
    end
  end

  def toyo_app_sync
    unless signed_in?
      session['current_access'] = request.fullpath
      redirect_to sign_in_path
      return
    end
    # KnowledgePortal上での東洋大学の識別子
    toyo_api_code = 'Zk3nT7Qz6BST49bsjNd9DE8xJs2yNdptlDe20csjvJxumyME'

    unless current_user.toyo_api_key.present? then
      uri = URI.parse("https://light-api.portal.ac/auth/login")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true

      req = Net::HTTP::Post.new(uri.path)
      req['x-university-token'] = toyo_api_code
      req['content-type'] = 'application/json'

      data = {
          'instance_id': 'eEA6c3ctKjc',
          'user_id': params['toyo_id'],
          'password': params['toyo_pw']
      }.to_json

      req.body = data
      response = http.request(req)
      result = JSON.parse(response.body)

      if result['is_successful'] = false then
        render plain:'ログインに失敗しました'
        return
      end

      api_key = result['result']['token']
      user = User.find_by_id(current_user.id)
      user.toyo_api_key = api_key
      user.save()
    else
      api_key = current_user.toyo_api_key
    end

    uri = URI.parse("https://light-api.portal.ac/class-schedule/my-schedule")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    req = Net::HTTP::Get.new(uri.path)
    req['x-university-token'] = toyo_api_code
    req['x-login-token'] = api_key

    response = http.request(req)
    result = JSON.parse(response.body)

    unless result['is_successful'] then
      render plain: '情報の取得に失敗しました'
      return
    end

    l_codes = []
    result['result']['items'].each do|reg_lecture|
      lecture = Lecture.where("REPLACE(REPLACE(title, ' ', ''),'　', '') ILIKE ?", "%#{reg_lecture['class_name']}%")
                .where(:week => reg_lecture['day_of_week'] - 1)
                .where(:time => reg_lecture['time_number'])
                .first()
      next unless lecture.present?

      l_codes.append(lecture.uuid)
    end

    user = User.find_by_id(current_user.id)
    user.registered_lectures = l_codes
    user.save()

    redirect_to my_lectures_path
  end
end

app/helpers/syllabus_helper.rb
module SyllabusHelper
end

app/views/syllabus/index.html.erb
<h2>時間割一覧</h2>
<form class="form" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="form-group">
    <label for="target_year">学年：</label>
    <select class="form-control" name="target_year" id="target_year">
      <option value="">---</option>
      <option value="1">1年</option>
      <option value="2">2年</option>
      <option value="3">3年</option>
      <option value="4">4年</option>
    </select>
    <% if params[:target_year].present? then %>
      <script>
        document.getElementById('target_year').value = '<%= params[:target_year] %>'
      </script>
    <% end %>
  </div>
  <div class="form-group">
    <label for="course">コース：</label>
    <select class="form-control" name="course" id="course">
      <option value="">---</option>
      <option value="0">共通</option>
      <option value="1">１年生</option>
      <option value="2">エンジニアリング</option>
      <option value="3">デザイン</option>
      <option value="4">ビジネス</option>
      <option value="5">シビル</option>
      <option value="6">未所属</option>
    </select>
    <% if params[:course].present? then %>
      <script>
          document.getElementById('course').value = '<%= params[:course] %>'
      </script>
    <% end %>
  </div>
  <div class="form-group">
    <label for="quarter">セメスタ/クォーター：</label>
    <select class="form-control" name="quarter" id="quarter">
      <option value="">---</option>
      <option value="spring">春学期</option>
      <option value="1">1Q</option>
      <option value="2">2Q</option>
      <option value="fall">秋学期</option>
      <option value="3">3Q</option>
      <option value="4">4Q</option>
    </select>
    <% if params[:quarter].present? then %>
      <script>
          document.getElementById('quarter').value = '<%= params[:quarter] %>'
      </script>
    <% end %>
  </div>
  <div class="form-group">
    <label for="title">科目名：</label>
    <input class="form-control" name="title" id="title">
    <% if params[:title].present? then %>
      <script>
          document.getElementById('title').value = '<%= params[:title] %>'
      </script>
    <% end %>
  </div>
  <div class="form-group">
    <label for="teacher">担当教員名：</label>
    <input class="form-control" name="teacher" id="teacher">
    <% if params[:teacher].present? then %>
      <script>
          document.getElementById('teacher').value = '<%= params[:teacher] %>'
      </script>
    <% end %>
  </div>
  <div class="form-group">
    <div>下級学年の科目を含めて検索する：<input type="checkbox" name="include_past_grade" id="include_past_grade"></div>
    <% if params[:include_past_grade] == "on" then %>
      <script>
          document.getElementById('include_past_grade').isOn = true;
      </script>
    <% end %>
  </div>
  <button class="btn btn-primary" onclick="submit();">検索</button>
  <input type="reset" class="btn btn-secondary">
</form>
<br>
<table class="table table-responsive table-condensed table-striped table-bordered">
  <thead>
    <tr>
      <th class="text-center">↓時間/曜日→</th>
      <th class="text-center">月</th>
      <th class="text-center">火</th>
      <th class="text-center">水</th>
      <th class="text-center">木</th>
      <th class="text-center">金</th>
      <th class="text-center">土</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="text-center">1限<br>9:00〜10:30</td>
      <% (0..5).each do|i| %>
        <td><% @data.select{|param| param.time == 1 and param.week == i }.each do|data| %>
            <p><a href="/lectures/<%= data.uuid %>"><%= data.title %></a></p>
          <% end %></td>
      <% end %>
    </tr>
    <tr>
      <td class="text-center">2限<br>10:40〜12:10</td>
      <% (0..5).each do|i| %>
        <td><% @data.select{|param| param.time == 2 and param.week == i }.each do|data| %>
            <p><a href="/lectures/<%= data.uuid %>"><%= data.title %></a></p>
          <% end %></td>
      <% end %>
    </tr>
    <tr>
      <td class="text-center">3限<br>13:00〜14:30</td>
      <% (0..5).each do|i| %>
        <td><% @data.select{|param| param.time == 3 and param.week == i }.each do|data| %>
            <p><a href="/lectures/<%= data.uuid %>"><%= data.title %></a></p>
          <% end %></td>
      <% end %>
    </tr>
    <tr>
      <td class="text-center">4限<br>14:45〜16:15</td>
      <% (0..5).each do|i| %>
        <td><% @data.select{|param| param.time == 4 and param.week == i }.each do|data| %>
            <p><a href="/lectures/<%= data.uuid %>"><%= data.title %></a></p>
          <% end %></td>
      <% end %>
    </tr>
    <tr>
      <td class="text-center">5限<br>16:30〜18:00</td>
      <% (0..5).each do|i| %>
        <td><% @data.select{|param| param.time == 5 and param.week == i }.each do|data| %>
            <p><a href="/lectures/<%= data.uuid %>"><%= data.title %></a></p>
          <% end %></td>
      <% end %>
    </tr>
    <tr>
      <td class="text-center">6限<br>18:15〜19:45</td>
      <% (0..5).each do|i| %>
        <td><% @data.select{|param| param.time == 6 and param.week == i }.each do|data| %>
            <p><a href="/lectures/<%= data.uuid %>"><%= data.title %></a></p>
          <% end %></td>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/syllabus/my_lecture.html.erb
<h2>履修メモ</h2>
<br>
<a href="<%= sync_toyo_app_path %>" class="btn btn-outline-primary">東洋大学アプリ連携</a>
<hr>
<table class="table table-responsive table-condensed table-striped table-bordered">
  <thead>
  <tr>
    <th class="text-center">↓時間/曜日→</th>
    <th class="text-center">月</th>
    <th class="text-center">火</th>
    <th class="text-center">水</th>
    <th class="text-center">木</th>
    <th class="text-center">金</th>
    <th class="text-center">土</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td class="text-center">1限<br>9:00〜10:30</td>
    <% (0..5).each do|i| %>
      <td><% @data.select{|param| param.time == 1 and param.week == i }.each do|data| %>
          <p><a href="/lectures/<%= data.uuid %>"><%= data.title %></a></p>
        <% end %></td>
    <% end %>
  </tr>
  <tr>
    <td class="text-center">2限<br>10:40〜12:10</td>
    <% (0..5).each do|i| %>
      <td><% @data.select{|param| param.time == 2 and param.week == i }.each do|data| %>
          <p><a href="/lectures/<%= data.uuid %>"><%= data.title %></a></p>
        <% end %></td>
    <% end %>
  </tr>
  <tr>
    <td class="text-center">3限<br>13:00〜14:30</td>
    <% (0..5).each do|i| %>
      <td><% @data.select{|param| param.time == 3 and param.week == i }.each do|data| %>
          <p><a href="/lectures/<%= data.uuid %>"><%= data.title %></a></p>
        <% end %></td>
    <% end %>
  </tr>
  <tr>
    <td class="text-center">4限<br>14:45〜16:15</td>
    <% (0..5).each do|i| %>
      <td><% @data.select{|param| param.time == 4 and param.week == i }.each do|data| %>
          <p><a href="/lectures/<%= data.uuid %>"><%= data.title %></a></p>
        <% end %></td>
    <% end %>
  </tr>
  <tr>
    <td class="text-center">5限<br>16:30〜18:00</td>
    <% (0..5).each do|i| %>
      <td><% @data.select{|param| param.time == 5 and param.week == i }.each do|data| %>
          <p><a href="/lectures/<%= data.uuid %>"><%= data.title %></a></p>
        <% end %></td>
    <% end %>
  </tr>
  <tr>
    <td class="text-center">6限<br>18:15〜19:45</td>
    <% (0..5).each do|i| %>
      <td><% @data.select{|param| param.time == 6 and param.week == i }.each do|data| %>
          <p><a href="/lectures/<%= data.uuid %>"><%= data.title %></a></p>
        <% end %></td>
    <% end %>
  </tr>
  </tbody>
</table>

app/views/syllabus/show.html.erb
<h2>時間割詳細</h2>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<div class="twitter">
  　<a href="//twitter.com/share" class="twitter-share-button" data-text="" data-url="https://schedule.iniad.dev<%= request.fullpath %>" data-lang="ja">
  Tweet
</a>
</div>
<table class="table table-responsive table-condensed table-striped table-bordered">
  <tbody>
    <tr>
      <th>科目名</th>
      <td><%= @data.title %></td>
    </tr>
      <th>担当教員</th>
      <td><%= @teachers %></td>
    </tr>
      <th>学期・クォーター</th>
      <td><%= @quarter %></td>
    </tr>
      <th>曜日・時間</th>
      <td><%= @time %></td>
    </tr>
      <th>受講可能学年</th>
      <td><%= @available_grade %></td>
    </tr>
    <tr>
      <th>教室</th>
      <td><%= @room %></td>
    </tr>
  </tbody>
</table>
<hr>
<% if signed_in? then %>
  <div id="checkmark_form_area">
    <form id="checkmark_form" action="/lectures/<%= params[:id] %>/check" method="post">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <div class="form-check">
        <% if current_user.registered_lectures.include?(params[:id]) %>
          <input class="form-check-input" type="checkbox" id="is_register" name="is_register" checked>
        <% else %>
          <input class="form-check-input" type="checkbox" id="is_register" name="is_register">
        <% end %>
        <label class="form-check-label" for="is_register">
          履修する
        </label>
      </div>
    </form>
    <script>
        $("#is_register").change(function(){
            $("#checkmark_form").submit();
        });
    </script>
  </div>
<% else %>
  <div id="checkmark_form_area">
    <p>履修メモを利用するには、<a href="<%= sign_in_path %>">INIADアカウントでサインイン</a>してください</p>
  </div>
<% end %>

app/views/syllabus/toyo_app_login.html.erb
<h2>東洋大学アプリ連携</h2>
<div class="alert alert-warning">
  <p>東洋大学の統合IDとパスワードを入力することで、実際に履修登録した情報を反映させることができます。</p>
  <p>統合IDとパスワードを使用したサードパーティー製アプリに関しては、<a href="https://www.toyo.ac.jp/ja-JP/news/students/20200305_attention/" >大学より注意喚起がなされています。</a></p>
  <p>このアプリでは、以下のポリシーにて、統合IDとパスワードを使用します。</p>
  <ul>
    <li>入力された統合IDとパスワードは、東洋大学アプリのAPIキーと引き換えるために使用します</li>
    <li>東洋大学アプリのAPIキーは、次回以降の同期に使用するため、ユーザーのアカウント情報と紐付けられて保存されます</li>
    <li>APIキー保存後は、APIキーのみを用いて通信を行い、統合IDとパスワードは破棄されます</li>
  </ul>
  <p>アプリ開発者は、統合IDとパスワードを速やかに破棄するように運用しておりますが、利用の際はあくまで自己責任においてご利用ください。</p>
</div>
<hr>
<form action="" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <% unless current_user.toyo_api_key.present? then %>
    <div class="form-group">
      <label for="toyo_id">ユーザーID：</label>
      <input class="form-control" id="toyo_id" name="toyo_id" type="text" placeholder="s1F10xxxxxxx">
    </div>
    <div class="form-group">
      <label for="toyo_pw">パスワード：</label>
      <input class="form-control" id="toyo_pw" name="toyo_pw" type="password" placeholder="">
    </div>
    <button type="submit" class="btn btn-primary">登録</button>
  <% else %>
    <button type="submit" class="btn btn-primary">同期</button>
  <% end %>
</form>