config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/' => redirect('/lectures')
  get '/lectures', to: 'syllabus#index'
  post '/lectures', to: 'syllabus#index'
  get '/lectures/:id', to: 'syllabus#show'
  post '/lectures/:uuid/check', to: 'syllabus#check_lecture'
  get '/my-lectures', to: 'syllabus#my_lecture'
  post '/my-lectures', to: 'syllabus#my_lecture'
  get  '/sync-toyo-app', to: 'syllabus#toyo_app_login'
  post '/sync-toyo-app', to: 'syllabus#toyo_app_sync'

  scope :auth do
    get '/sign_in', to: 'auth#login'
    get '/callback', to: 'auth#callback'
    get '/sign_out', to: 'auth#logout'
  end

  scope :teachers do
    get '/', to: 'teacher#index'
    get '/:id', to: 'teacher#show'
  end

  get 'about', to: 'application#about'
  get 'health', to: 'application#health'

  scope :api do
    get 'keygen', to: 'api#generate_key'

    scope 'my-lectures' do
      get '/', to: 'api#my_lectures'
    end

    scope 'lectures' do
      get '/', to: 'api#lectures'
      get '/:uuid', to: 'api#lecture'
    end

    scope 'teachers' do
      get '/', to: 'api#teachers'
      get '/:uuid', to: 'api#teacher'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>INIAD時間割</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.js"
      integrity="sha256-BTlTdQO9/fascB1drekrDVkaKd9PkwBymMlHOiG+qLI="
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-161682303-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-161682303-1');
    </script>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="">INIAD時間割</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="/lectures">時間割一覧</a>
          <a class="nav-item nav-link" href="/my-lectures">履修メモ</a>
          <a class="nav-item nav-link" href="/about">このアプリについて</a>
        </ul>
        <ul class="navbar-nav">
          <% if signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button">Welcome! <%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a class="nav-link" href="#">アカウント情報</a></li>
                <li><a class="nav-link" href="#">デバイス管理</a></li>
                <% if current_user.role == "admin" then %>
                  <li><a class="nav-link" href="#">ユーザー管理</a></li>
                <% end %>
              </ul>
            </li>
            <a class="nav-item nav-link" href="<%= sign_out_path %>">サインアウト</a>
          <% else %>
            <a class="nav-item nav-link" href="<%= sign_in_path %>">サインイン</a>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>